# Generated by Django 5.2.4 on 2025-07-04 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
